/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.bankgui;

import cz.fi.muni.pv168.bank.Account;
import cz.fi.muni.pv168.bank.AccountManager;
import cz.fi.muni.pv168.bank.Person;
import java.util.ResourceBundle;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Aneta Moravcikova, Katarina Matusova
 */
public class AddAccountFrame extends javax.swing.JFrame {

    
    private JDialog dialog;
    private JFrame parent;
    private Person owner;
    private AccountManager manager;    
    private final ResourceBundle bundle;
    private final static Logger log = LoggerFactory.getLogger(AddAccountFrame.class);

    /**
     * Creates new form AddAccountFrame
     */
    public AddAccountFrame(AccountManager manager, JFrame parent, Person owner, ResourceBundle bundle) {
        this.manager = manager;
        this.parent =  parent;
        this.owner = owner;
        this.bundle = bundle;
        this.setTitle(bundle.getString("addAccount"));
        initComponents();
    }                     
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAccountButton = new javax.swing.JButton();
        noteTextField = new javax.swing.JTextField();
        initBalance = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        addAccountButton.setText(bundle.getString("addAccount"));
        addAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccountButtonActionPerformed(evt);
            }
        });

        jLabel1.setText(bundle.getString("addInitialBalance"));

        jLabel2.setText(bundle.getString("addNote"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addAccountBigger.png"))); // NOI18N
        jLabel3.setText(bundle.getString("addAccount"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(addAccountButton)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(initBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(noteTextField))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(initBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(addAccountButton)
                .addGap(46, 46, 46))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {initBalance, noteTextField});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccountButtonActionPerformed
        Account acc = new Account();
        acc.setNote(noteTextField.getText());
        String balanceString = initBalance.getText();
        
        if (balanceString.isEmpty()){
            acc.setBalance(0.0);
        } else {
            try {
                double balance = Double.parseDouble(balanceString);
                acc.setBalance(balance);
            } catch (NumberFormatException ex) {
                log.error("Balance not double");
                JOptionPane.showMessageDialog(rootPane, "Balance must be double number.");
                return;
            }
        }
        manager.createAccount(acc);
        AccountTableModel model = (AccountTableModel) ((AccountsFrame) parent).getTable().getModel();
        model.addAccount(acc);
        this.setVisible(false);
    }//GEN-LAST:event_addAccountButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAccountButton;
    private javax.swing.JTextField initBalance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField noteTextField;
    // End of variables declaration//GEN-END:variables
}