/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.bankgui;

import cz.fi.muni.pv168.bank.Person;
import cz.fi.muni.pv168.bank.PersonManager;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.ResourceBundle;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Katarina Matusova
 */
public class AddClientFrame extends javax.swing.JFrame {

    private final JFrame parent;
    private JDialog dialog;
    private static PersonManager personManager;
    private final ResourceBundle bundle;
    private final static Logger log = LoggerFactory.getLogger(AddClientFrame.class);

    /**
     * Creates new form AddClientFrame
     *
     * @param personManager
     * @param parent
     * @param bundle
     */
    public AddClientFrame(PersonManager personManager, JFrame parent, ResourceBundle bundle) {
        AddClientFrame.personManager = personManager;
        this.bundle = bundle;
        this.parent = parent;
        this.setTitle(bundle.getString("addClient"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        nameField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        bornLabel = new javax.swing.JLabel();
        addClientLabel = new javax.swing.JLabel();
        datePicker = new org.jdesktop.swingx.JXDatePicker();

        setBackground(new java.awt.Color(153, 153, 255));

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        addButton.setText(bundle.getString("addClient")
        );
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText(bundle.getString("name") + " : "
        );

        bornLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bornLabel.setText(bundle.getString("born") + " : ");

        addClientLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addClientLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addContact.png"))); // NOI18N
        addClientLabel.setText(bundle.getString("addClient")
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bornLabel)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(addButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(addClientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(addClientLabel)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bornLabel)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(addButton)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Person person = new Person();
        if (nameField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Fill in all the details.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        person.setName(nameField.getText());
        if (datePicker.getDate() != null) {
            Date born = datePicker.getDate();
            LocalDate bornn = born.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            if (bornn.isAfter(LocalDate.now())) {
                log.error("Born in future.");
                JOptionPane.showMessageDialog(rootPane, "Cannot be born in future.", "Format error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            person.setBorn(bornn);
            PersonTableModel model = (PersonTableModel) ((PeopleFrame) parent).getTable().getModel();
            model.addPerson(person);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Fill in all the details.", "Warning", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addClientLabel;
    private javax.swing.JLabel bornLabel;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
